### ISSUE TITLE
Chance of supporinng rainbow folder ? 

### ISSUE THREAD

**Issue by bale007** [MasyoLab/UnityTools-FavoritesAsset#55]
Hi MasyoLab,

Thank you for this incredible tools, it really helps me with my project development.

Just checking that is the supporting of displaying custom folder icon in your current development milestone ?

like this picture below:
![image](https://github.com/MasyoLab/UnityTools-FavoritesAsset/assets/44196725/bc366d4b-fc23-4c6c-ab90-103a54447099)

Regards,
Bale007

**Comment by MasyoLab** [comment]
Hi Bale007,

Thank you for using this tool!

It's great to know that there is such a wonderful tool like Rainbow Folders.

While direct support for this tool is not feasible, we have added a feature that allows you to specify the icon for display.

- [The latest release](https://github.com/MasyoLab/UnityTools-FavoritesAsset/releases/tag/v1.5.0)
- [Usage example](https://github.com/MasyoLab/UnityTools-FavoritesAsset/blob/master/Assets/Editor/Examples/RainbowFolders/FavoritesAssetWindowRainbowFoldersSupportExample.cs)

I used the discontinued [Unity3D Rainbow Folders](https://github.com/PhannGor/unity3d-rainbow-folders) for testing, but by extending it as shown in the example, you can enhance the display as illustrated in the image below.
![image](https://github.com/MasyoLab/UnityTools-FavoritesAsset/assets/20793765/fdb39afc-081e-47d4-8957-60e2a4e2eb02)

Are you using [Rainbow Folders 2](https://assetstore.unity.com/packages/tools/utilities/rainbow-folders-2-143526)?

I'm not sure if RainbowFoldersSettings.Instance.GetFolderIcon is a public function in this tool, but if the icon retrieval process used in the implementation of the folder icon drawing is a public function, it can be extended.

**Comment by bale007** [comment]
Hi Masyolab,

Thank you for your quick and detailed response!

Yes, I'm using Rainbow Folders 2, thank you for pointing out the icon customization feature in the latest release, I will take a look at the plugins and integrate them the way you suggested.

Regards,
Bale007

**Comment by bale007** [comment]
i managed to get the custom icon working by using the following code for Rainbow Folders 2, where item2 is the "small icon" for each folder.

In Rainbow Folders 2 you get to set background for each folder but i never used that feature so setting custom icon is more than enough for my case.

```
    private static Texture GetAssetIcon(string folderPath)
    {
        var rule = ProjectRuleset.Instance.GetRuleByPath(folderPath, true);
        if (rule == null)
        {
            return null;
        }

        return ProjectIconsStorage.GetIcons(rule.IconType).Item2;
    }
```

**Comment by MasyoLab** [comment]
It seems like the extension was successful! That's great.
